/* shared/floorData.js — 水牌（樓層公司名錄）預設資料
   由管理後台「水牌管理」維護，實際資料存於 localStorage bbs_floors 並同步至 GitHub。
   這裡是尚未設定過時的預設值，也是 screen10 / screen11 讀不到資料時的後備。
   樓層號碼決定顯示在哪一塊水牌：1~14 樓 → screen10，15 樓以上 → screen11。 */
(function () {
  'use strict';

  var DEFAULT_FLOORS = [
    {"floor":"1A","company":"永豐銀行-中科分行"},
    {"floor":"1B","company":"社團法人台灣基督教繁星協會"},
    {"floor":"2B","company":"社團法人台灣基督教繁星協會"},
    {"floor":"3A","company":"荷華達康生物科技(股)公司"},
    {"floor":"3B","company":"泰瑩科技(股)公司"},
    {"floor":"3C","company":"WORK HUB智能空間 | 稅管家"},
    {"floor":"4A","company":"威傑士國際開發有限公司"},
    {"floor":"4B","company":"寶漾國際(股)公司"},
    {"floor":"4C","company":"哈佛國際法律事務所"},
    {"floor":"4D","company":"連盈資訊服務有限公司"},
    {"floor":"4E","company":"PUPRIME"},
    {"floor":"4F","company":"山海邑 / 光明頂"},
    {"floor":"4G","company":"豐彩藝術(股)公司"},
    {"floor":"4H","company":"遠視界科技(股)公司"},
    {"floor":"5A","company":""},
    {"floor":"5B","company":"海格商務中心/班馬克國際"},
    {"floor":"5C","company":"橙杏商務顧問"},
    {"floor":"5D","company":"寰瀛法律事務所"},
    {"floor":"5E","company":"雷力科技股份有限公司"},
    {"floor":"5F","company":"也樂居保全(股)公司"},
    {"floor":"5G","company":"堃成營造(股)公司"},
    {"floor":"5H","company":"廣原行實業有限公司"},
    {"floor":"6A","company":"亞太資源集團 | 首創國際資本"},
    {"floor":"6B","company":"書香同城有限公司"},
    {"floor":"6C","company":"思瑞建築(股)有限公司"},
    {"floor":"6D","company":"定城實業有限公司"},
    {"floor":"6E","company":""},
    {"floor":"6F","company":""},
    {"floor":"6G","company":""},
    {"floor":"6H","company":""},
    {"floor":"7A","company":"眾醫生技科技(股)公司"},
    {"floor":"7B","company":"中信法律事務所"},
    {"floor":"7C","company":"蒼晟系統核心有限公司"},
    {"floor":"7D","company":"中鼎資訊科技有限公司"},
    {"floor":"7E","company":"璀璨年華投資股份有限公司"},
    {"floor":"7F","company":""},
    {"floor":"7G","company":""},
    {"floor":"7H","company":""},
    {"floor":"8A","company":""},
    {"floor":"8B","company":""},
    {"floor":"8C","company":"嵐宇科技(股)公司"},
    {"floor":"8D","company":"想想國際餐飲集團"},
    {"floor":"8E","company":"築藝坊室內裝修有限公司"},
    {"floor":"8F","company":"天空科技有限公司"},
    {"floor":"8G","company":"安永聯合會計師事務所"},
    {"floor":"8H","company":"安永聯合會計師事務所"},
    {"floor":"9A","company":"斯丹德企業有限公司"},
    {"floor":"9B","company":"智業有限公司"},
    {"floor":"9C","company":"志強國際企業股份有限公司"},
    {"floor":"9D","company":"台慈軸承有限公司"},
    {"floor":"9E","company":"騏璣資訊科技(股)公司"},
    {"floor":"9F","company":"S.F. Management Consulting LTD."},
    {"floor":"9G","company":""},
    {"floor":"9H","company":""},
    {"floor":"10A","company":"惠眾建設(股)公司"},
    {"floor":"10B","company":""},
    {"floor":"10C","company":"睿禾投資顧問(股)公司"},
    {"floor":"10D","company":""},
    {"floor":"10E","company":"大易空間計設有限公司"},
    {"floor":"10F","company":"鋐鏹工程顧問股份有限公司"},
    {"floor":"10G","company":""},
    {"floor":"10H","company":""},
    {"floor":"11A","company":"迅捷物流供應鏈股份有限公司"},
    {"floor":"11B","company":"橙杏顧問 / 眾勤國際"},
    {"floor":"11C","company":"愛生育生物科技(股)公司"},
    {"floor":"11D","company":"台灣木工機械工業同業公會"},
    {"floor":"11E","company":"遠雄房地產發展股份有限公司"},
    {"floor":"11F","company":""},
    {"floor":"11G","company":""},
    {"floor":"11H","company":"崴寶精密科技(股)公司"},
    {"floor":"12A","company":""},
    {"floor":"12B","company":"黑本艾美影像設計有限公司"},
    {"floor":"12C","company":""},
    {"floor":"12D","company":"浩信聯合會計師事務所"},
    {"floor":"12E","company":""},
    {"floor":"12F","company":""},
    {"floor":"12G","company":"創客共好商務中心"},
    {"floor":"12H","company":"創客共好商務中心"},
    {"floor":"13A","company":"白水國際商務中心"},
    {"floor":"13B","company":"昕格聯合辦公空間"},
    {"floor":"13C","company":"創客共好商務中心"},
    {"floor":"13D","company":"京固國際通商有限公司"},
    {"floor":"13E","company":"技成科技(股)公司"},
    {"floor":"13F","company":"鼎格行銷有限公司"},
    {"floor":"13G","company":""},
    {"floor":"13H","company":""},
    {"floor":"14A","company":""},
    {"floor":"14B","company":""},
    {"floor":"14C","company":""},
    {"floor":"14D","company":"勤業投資(股)公司"},
    {"floor":"14E","company":"勤業投資(股)公司"},
    {"floor":"14F","company":""},
    {"floor":"14G","company":"京宇法律事務所 / 長福會計"},
    {"floor":"14H","company":"精聯保險經紀人(股)公司"},
    {"floor":"15A","company":"能匠自動化機械(股)公司"},
    {"floor":"15B","company":"聖昌益整合有限公司"},
    {"floor":"15C","company":"利璟投資有限公司"},
    {"floor":"15D","company":"君鴻不動產估價師/地政士"},
    {"floor":"15E","company":"睿群集團 / 敬虔法律"},
    {"floor":"15F","company":"呈嘉工程有限公司"},
    {"floor":"15G","company":"艾朵傳媒有限公司"},
    {"floor":"15H","company":"花緹生技美容國際有限公司"},
    {"floor":"16A","company":"親家建設(股)公司"},
    {"floor":"17A","company":"鼎京科技有限公司"},
    {"floor":"17B","company":""},
    {"floor":"17C","company":"亞昕集團 台中分公司"},
    {"floor":"17D","company":"亞昕集團 台中分公司"},
    {"floor":"17E","company":"景得整合設計有限公司"},
    {"floor":"17F","company":"宸鈊有限公司"},
    {"floor":"17G","company":"光銳事業股份有限公司"},
    {"floor":"17H","company":""},
    {"floor":"18A","company":"代代木國際精品(股)公司"},
    {"floor":"18B","company":"香港商亞莉奈有限公司"},
    {"floor":"18C","company":""},
    {"floor":"18D","company":"MUFU 台灣微米科技"},
    {"floor":"18E","company":"和泰保險經紀人 和群 / 宏亞"},
    {"floor":"18F","company":"和泰保險經紀人 台中 / 美成"},
    {"floor":"18G","company":"和泰保險經紀人"},
    {"floor":"18H","company":"紳格室內裝修設計有限公司"},
    {"floor":"19A","company":"豐穀建設開發(股)公司"},
    {"floor":"19B","company":"豐安營造工程(股)公司"},
    {"floor":"19C","company":"春耕不動產經紀(股)公司"},
    {"floor":"19D","company":"春耕不動產經紀(股)公司"},
    {"floor":"19E","company":"地方建築有限公司"},
    {"floor":"19F","company":"捷康生技股份有限公司"},
    {"floor":"19G","company":"捷康生技股份有限公司"},
    {"floor":"19H","company":"捷康生技股份有限公司"},
    {"floor":"20A","company":"臺中市不動產","group":"不動產公會"},
    {"floor":"20B","company":"建築開發商業","group":"不動產公會"},
    {"floor":"20C","company":"同業公會","group":"不動產公會"},
    {"floor":"20D","company":""},
    {"floor":"20E","company":"Reconfort"},
    {"floor":"20F","company":"瑞博企業有限公司"},
    {"floor":"20G","company":"浚創管理顧問有限公司"},
    {"floor":"20H","company":"萬智匯行銷電商基地"},
    {"floor":"21A","company":""},
    {"floor":"22A","company":"永華聯合會計師事務所"},
    {"floor":"22B","company":"永華聯合會計師事務所"},
    {"floor":"22C","company":"金開(股)公司"},
    {"floor":"22D","company":"快思(股)公司"},
    {"floor":"22E","company":"ARA Fine Jewellery"},
    {"floor":"22F","company":"南榮貿易(股)公司"},
    {"floor":"22G","company":"采義科技有限公司"},
    {"floor":"22H","company":"茂居建設有限公司 / 富居營造(股)公司"},
    {"floor":"23A","company":"星穎國際顧問有限公司"},
    {"floor":"23B","company":""},
    {"floor":"23C","company":""},
    {"floor":"23D","company":"駿亞生醫科技(股)公司"},
    {"floor":"23E","company":"奕昇有限公司 / 大禾設計"},
    {"floor":"23F","company":""},
    {"floor":"23G","company":""},
    {"floor":"23H","company":"賽席爾商盈創有限公司"},
    {"floor":"24A","company":"群創事業有限公司"},
    {"floor":"24B","company":""},
    {"floor":"24C","company":"橋締國際有限公司"},
    {"floor":"24D","company":"大峽谷照明系統集團"},
    {"floor":"24E","company":"德馨投顧"},
    {"floor":"24F","company":""},
    {"floor":"24G","company":""},
    {"floor":"24H","company":"新陽能源 / 新科開發"},
    {"floor":"25A","company":"允將建設(股)公司"},
    {"floor":"26A","company":"安永聯合會計師事務所"},
    {"floor":"26B","company":"安永聯合會計師事務所"},
    {"floor":"27A","company":""},
    {"floor":"28A","company":"永豐商業銀行(股)公司"},
  ];

  /* 從「15A」這種樓層代號取出樓層數字，取不到時回傳 0（會歸到第一塊水牌） */
  function floorNum(floor) {
    var n = parseInt(String(floor || ''), 10);
    return isNaN(n) ? 0 : n;
  }

  window.FloorData = { DEFAULT_FLOORS: DEFAULT_FLOORS, floorNum: floorNum };
})();
